In [2]:
import numpy as np
import pandas as pd

In [3]:
cartyresDf  = pd.read_csv("../CarTyres_data.csv")
cartyresDf.head()

,Run,Sears,Goodyear,Goodrich,Price50,Price60,Price70,Miles30K,Miles40K,Miles50K,SideBlack,SideWhite,Utility
0,1,1,0,0,1,0,0,1,0,0,0,1,5.2
1,2,1,0,0,0,1,0,0,1,0,0,1,7.3
2,3,1,0,0,0,0,1,0,0,1,1,0,5.7
3,4,0,1,0,0,1,0,1,0,0,1,0,4.8
4,5,0,1,0,0,0,1,0,1,0,0,1,7.2

In [4]:
cartyresDf.shape

(18, 13)

# Calculate part worth utility

In [7]:
import statsmodels.api as sm

In [8]:
X = cartyresDf[["Sears",
                     "Goodyear",
                     "Goodrich",
                     "Price50",
                     "Price60",
                     "Price70",
                     "Miles30K",
                     "Miles40K",
                     "Miles50K",
                     "SideBlack",
                     "SideWhite"]]
#X = sm.add_constant(X)
Y = cartyresDf.Utility
linearRegression = sm.OLS(Y, X).fit()
linearRegression.summary()

/Users/srimugunthan/anaconda3/envs/cloned_basepy388/lib/python3.8/site-packages/scipy/stats/stats.py:1541: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=18
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                Utility   R-squared:                       0.971
Model:                            OLS   Adj. R-squared:                  0.950
Method:                 Least Squares   F-statistic:                     47.00
Date:                Sun, 09 Apr 2023   Prob (F-statistic):           7.39e-07
Time:                        12:31:44   Log-Likelihood:                -8.7377
No. Observations:                  18   AIC:                             33.48
Df Residuals:                      10   BIC:                             40.60
Df Model:                           7
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Sears          1.6935      0.178      9.500      0.000       1.296       2.091
Goodyear       2.6102      0.178     14.643      0.000       2.213       3.007
Goodrich      -0.6731      0.178     -3.776      0.004      -1.070      -0.276
Price50        1.8602      0.178     10.435      0.000       1.463       2.257
Price60        1.6269      0.178      9.126      0.000       1.230       2.024
Price70        0.1435      0.178      0.805      0.439      -0.254       0.541
Miles30K      -0.8565      0.178     -4.805      0.001      -1.254      -0.459
Miles40K       1.8102      0.178     10.155      0.000       1.413       2.207
Miles50K       2.6769      0.178     15.017      0.000       2.280       3.074
SideBlack      1.2028      0.152      7.899      0.000       0.863       1.542
SideWhite      2.4278      0.124     19.527      0.000       2.151       2.705
==============================================================================
Omnibus:                        2.753   Durbin-Watson:                   1.714
Prob(Omnibus):                  0.253   Jarque-Bera (JB):                1.287
Skew:                          -0.632   Prob(JB):                        0.525
Kurtosis:                       3.342   Cond. No.                     3.16e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 2.84e-32. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [9]:
coeff =linearRegression.params.to_dict()
attrarray = {
'brand' : ['Sears','Goodyear','Goodrich'],
'Price' : ['Price50','Price60','Price70'],
'Miles' : ['Miles30K','Miles40K','Miles50K'],
'Side' : ['SideBlack','SideWhite']
}

part_worth_utility ={}
for attribute in attrarray.keys():
    print('\nAttribute:', attribute)
    temp_list = attrarray[attribute]
    for k in temp_list:
        part_worth_utility[k] =  coeff[k]
        print('       ',k, format(part_worth_utility[k], '.2f'))
# print(part_worth_utility)

Attribute: brand
        Sears 1.69
        Goodyear 2.61
        Goodrich -0.67

Attribute: Price
        Price50 1.86
        Price60 1.63
        Price70 0.14

Attribute: Miles
        Miles30K -0.86
        Miles40K 1.81
        Miles50K 2.68

Attribute: Side
        SideBlack 1.20
        SideWhite 2.43

In [10]:
part_worth_utility

{'Sears': 1.6935185185185206,
 'Goodyear': 2.6101851851851903,
 'Goodrich': -0.6731481481481434,
 'Price50': 1.8601851851851858,
 'Price60': 1.6268518518518524,
 'Price70': 0.1435185185185195,
 'Miles30K': -0.8564814814814833,
 'Miles40K': 1.8101851851851838,
 'Miles50K': 2.6768518518518514,
 'SideBlack': 1.2027777777777817,
 'SideWhite': 2.427777777777779}

In [11]:

partworth_range = {}
for attribute in attrarray.keys():
    temp_list = attrarray[attribute]
    tempRange = []
    for k in temp_list:
        if k in coeff.keys():
            tempRange.append(coeff[k])
    partworth_range[attribute] = tempRange
print ("--"*10)
print("\nPartworth range",partworth_range )
importance = {}
relative_importance = {}
for key, v in  partworth_range.items():
    importance[key] = ( max(v) - min(v))
total_of_imp_values = sum(importance.values())
for key,val in importance.items():
    relative_importance[key] = (100* round(val/total_of_imp_values,3))
    
# print("\nImportance",importance)
# print("\nRelative Importance",relative_importance)
print ("--"*10)
print ("Importance of Feature:\n brand:",format(importance['brand'],'.2f'),\
"\nPrice:", format(importance['Price'], '.2f'),  "\nMiles:", format(importance['Miles'],'.2f'), \
      "\nSide:", format(importance['Side'],'.2f'))

print ("--"*10)
print ("\nRelative Importance of Feature:\n brand:",format(relative_importance['brand'], '.2f'), "%",\
"\nPrice:",format(relative_importance['Price'], '.2f') , "%", \
       "\nMiles:", format(relative_importance['Miles'], '.2f'), "%",\
       "\nSide:", format(relative_importance['Side'], '.2f') , "%\n")
print ("--"*10)

--------------------

Partworth range {'brand': [1.6935185185185206, 2.6101851851851903, -0.6731481481481434], 'Price': [1.8601851851851858, 1.6268518518518524, 0.1435185185185195], 'Miles': [-0.8564814814814833, 1.8101851851851838, 2.6768518518518514], 'Side': [1.2027777777777817, 2.427777777777779]}
--------------------
Importance of Feature:
 brand: 3.28
Price: 1.72
Miles: 3.53
Side: 1.22
--------------------

Relative Importance of Feature:
 brand: 33.60 %
Price: 17.60 %
Miles: 36.20 %
Side: 12.60 %

--------------------

# Optimal bundle utility

In [17]:

optBundle = [0,1,0,0,0,0,0,0,1,0,1]
print ("The optimal feature bundle   would have the  utility:",\
linearRegression.predict(optBundle)[0])

The optimal feature bundle   would have the  utility: 7.714814814814821

In [18]:
7.7 * 16.3

125.51

# Market share simulation

In [21]:
cartyresDf.columns

Index(['Run', 'Sears', 'Goodyear', 'Goodrich', 'Price50', 'Price60', 'Price70',
       'Miles30K', 'Miles40K', 'Miles50K', 'SideBlack', 'SideWhite',
       'Utility'],
      dtype='object')

In [27]:
cpcarTyresDf

,Run,Sears,Goodyear,Goodrich,Price50,Price60,Price70,Miles30K,Miles40K,Miles50K,SideBlack,SideWhite,predictedUtility
0,1,1,0,0,0,0,0,1,0,0,0,1,3.264815
1,2,1,0,0,0,0,0,0,1,0,0,1,5.931481
2,3,1,0,0,0,0,0,0,0,1,1,0,5.573148
3,4,0,1,0,0,0,0,1,0,0,1,0,2.956481
4,5,0,1,0,0,0,0,0,1,0,0,1,6.848148
5,6,0,1,0,0,0,0,0,0,1,0,1,7.714815
6,7,0,0,1,0,0,0,1,0,0,0,1,0.898148
7,8,0,0,1,0,0,0,0,1,0,1,0,2.339815
8,9,0,0,1,0,0,0,0,0,1,0,1,4.431481
9,10,1,0,0,0,0,0,1,0,0,1,0,2.039815
10,11,1,0,0,0,0,0,0,1,0,0,1,5.931481
11,12,1,0,0,0,0,0,0,0,1,0,1,6.798148
12,13,0,1,0,0,0,0,1,0,0,0,1,4.181481
13,14,0,1,0,0,0,0,0,1,0,1,0,5.623148
14,15,0,1,0,0,0,0,0,0,1,0,1,7.714815
15,16,0,0,1,0,0,0,1,0,0,0,1,0.898148
16,17,0,0,1,0,0,0,0,1,0,0,1,3.564815
17,18,0,0,1,0,0,0,0,0,1,1,0,3.206481

In [31]:
cpcarTyresDf = cartyresDf.copy()

ignorepricecols = ["Price50","Price60","Price70"]
for col in ignorepricecols:
    cpcarTyresDf[col] = 0
cpcarTyresDf = cpcarTyresDf.drop(["Utility"],axis=1)
X = cpcarTyresDf[["Sears",
                     "Goodyear",
                     "Goodrich",
                     "Price50",
                     "Price60",
                     "Price70",
                     "Miles30K",
                     "Miles40K",
                     "Miles50K",
                     "SideBlack",
                     "SideWhite"]]
predictUtil = linearRegression.predict(X)
cpcarTyresDf["predictedUtility"] = predictUtil
utility_values = list(cpcarTyresDf["predictedUtility"].values)
total_utility=0
for val in utility_values:
    total_utility = total_utility + np.exp(val)
market_shares =[]
for val in utility_values:
    probability = np.exp(val)/total_utility
    market_shares.append(probability*100)
cpcarTyresDf["market_share"]  = market_shares
cpcarTyresDf[["Sears",
                     "Goodyear",
                     "Goodrich",
                     "Miles30K",
                     "Miles40K",
                     "Miles50K",
                     "SideBlack",
                     "SideWhite",
                     "predictedUtility",
                     "market_share"]].drop_duplicates()

,Sears,Goodyear,Goodrich,Miles30K,Miles40K,Miles50K,SideBlack,SideWhite,predictedUtility,market_share
0,1,0,0,1,0,0,0,1,3.264815,0.331655
1,1,0,0,0,1,0,0,1,5.931481,4.773155
2,1,0,0,0,0,1,1,0,5.573148,3.335672
3,0,1,0,1,0,0,1,0,2.956481,0.243657
4,0,1,0,0,1,0,0,1,6.848148,11.937376
5,0,1,0,0,0,1,0,1,7.714815,28.398631
6,0,0,1,1,0,0,0,1,0.898148,0.031107
7,0,0,1,0,1,0,1,0,2.339815,0.131512
8,0,0,1,0,0,1,0,1,4.431481,1.065035
9,1,0,0,1,0,0,1,0,2.039815,0.097426
11,1,0,0,0,0,1,0,1,6.798148,11.355183
12,0,1,0,1,0,0,0,1,4.181481,0.829450
13,0,1,0,0,1,0,1,0,5.623148,3.506696
16,0,0,1,0,1,0,0,1,3.564815,0.447688
17,0,0,1,0,0,1,1,0,3.206481,0.312862